-- Crear la tabla de Odontólogos
DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    MATRICULA INT NOT NULL,
    ESPECIALIDAD VARCHAR(100) NOT NULL
);

-- Insertar datos de prueba
INSERT INTO ODONTOLOGOS (NOMBRE, APELLIDO, MATRICULA, ESPECIALIDAD)
VALUES
    ('María', 'López', 12345, 'Ortodoncia'),
    ('Juan', 'Gómez', 54321, 'Cirugía Maxilofacial');